// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"OrangeMapshotMZ","status":true,"description":"This plugin will save a picture of the entire map on a Mapshots folder when you press a key. <OrangeMapshotMZ>","parameters":{"useMapName":"true","layerType":"0","drawAutoShadows":"true","drawEvents":"true","keyCode":"44","imageType":"png","imageQuality":"100","imagePath":"C:\\Users\\Note\\Documents\\Projeto Femilla - Boardgames\\A Freya to the Past"}}
];
